modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/LtxProgrammer/Changed-Minecraft-Mod/issues" #optional

[[mods]]
modId="changed"
version="0.13.1"
displayName="Changed: Minecraft Mod"
updateJSONURL="https://raw.githubusercontent.com/LtxProgrammer/Changed-Minecraft-Mod/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/changed-minecraft-mod"
logoFile="icon@400.png"
credits='''DragonSnow, bijimio, Yird, Valurio9683, KoBOLTA, poptartiguess, N1CO785, BaiTian6641, Artemka2009, Foxyas, Crepe2806, xxXMinionXxx, Sel7D4, Candnhen, ABTOR, Twix#5803, dahotdogdesant'''
authors="LtxProgrammer"
description='''Gooey transfur mod inspired by Dragon Snow's Changed.'''
[[dependencies.changed]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.changed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
